parameters:
  skip: false

steps:
  - task: AzureCLI@1
    displayName: 'Run Unit Tests'
    env:
      TF_VAR_remote_state_container: $(TF_VAR_remote_state_container)
      TF_VAR_remote_state_account: $(TF_VAR_remote_state_account)
      TF_VAR_cosmosdb_replica_location: $(TF_VAR_cosmosdb_replica_location)
      TF_VAR_resource_group_location: $(TF_VAR_resource_group_location)
      TF_VAR_elasticsearch_username: $(elastic-username-${{ parameters.terraformWorkspacePrefix }}-${{ parameters.environmentName }})
      TF_VAR_elasticsearch_password: $(elastic-password-${{ parameters.terraformWorkspacePrefix }}-${{ parameters.environmentName }})
      TF_VAR_elasticsearch_endpoint: $(elastic-endpoint-${{ parameters.terraformWorkspacePrefix }}-${{ parameters.environmentName }})

    condition: not(coalesce(variables.SKIP_TESTS, ${{ parameters.skip }}))
    inputs:
      azureSubscription: '$(SERVICE_CONNECTION_NAME)'
      addSpnToEnvironment: true
      scriptLocation: inlineScript
      inlineScript: |
        #!/usr/bin/env bash
        set -euo pipefail

        export ARM_TENANT_ID=$tenantId
        export ARM_CLIENT_SECRET=$servicePrincipalKey
        export ARM_CLIENT_ID=$servicePrincipalId
        export ARM_ACCESS_KEY=$(az storage account keys list --subscription "$ARM_SUBSCRIPTION_ID" --account-name "$(TF_VAR_remote_state_account)" --query "[0].value" --output tsv)
        cd "$ARTIFACT_ROOT"/"$TERRAFORM_TEMPLATE_PATH"

        # Setting the scripts to be run as executable
        chmod -fR 755 *.sh || true

        go test -v $(go list ./... | grep "$TERRAFORM_TEMPLATE_PATH" | grep "unit")
